### PR TITLE
react: add to track

### PR DESCRIPTION
**Pull request by petertseng**
Reviewers: Please note that this contains all commits from #31. This is because I am not willing to contribute an exercise without Travis proving that the example implementation I provide is correct. So either:

* #31 should be merged first, and then this PR
* or #30 should merged first and ask me to rebase this PR, which I will, then merge this PR

### CODE REVIEW

**Comment by petertseng** [comment]
If @exercism/dlang will not review this, then what will we do?

**Comment by kytrinyx** [comment]
@petertseng Would you mind rebasing this PR? I'm going to go ahead and bring it in.

**Comment by petertseng** [comment]
👍

**Comment by petertseng** [comment]
👍 rebased.

(For my use: `git diff f263d60 232c61f` looks like what I expect)

**Comment by kytrinyx** [comment]
Thanks, @petertseng!

**Pull request merged**
